# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: handy_customers_development
  username: postgres
  password: 1234
  host: localhost
  port: 5432

# production:
#   <<: *default
#   database: server_production
#   username: server
#   password: <%= ENV['SERVER_DATABASE_PASSWORD'] %>
